# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.2.2'
gem 'rails'

group :development, :test do
  gem 'byebug'
  gem 'launchy'
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  gem 'rubycritic', require: false
  gem 'sqlite3'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'rspec-rails'
  gem 'cucumber-rails', require: false
  gem 'rails-controller-testing'
  gem 'simplecov', require: false
  gem 'ZenTest'
end

group :production do
  gem 'pg'
end

gem 'jquery-rails'
gem 'sass-rails'
gem 'uglifier'

gem 'net-imap', require: false
gem 'net-pop', require: false
gem 'net-smtp', require: false
